
DQN_PARAMS = {
    "VizdoomDefendCenter-v0": {
        "batch_size": 32,
        "learning_rate": 0.0001,
        "buffer_size": 15000,
        "gamma": 0.92,
        "exploration_fraction": 0.28,
        "exploration_final_eps": 0.016,
        "learning_starts": 1e4,
        "decay_start_steps": 0,
        "decay_end_steps": 1.5e5,
    },
    "VizdoomDefendLine-v0": {
        "batch_size": 32,
        "learning_rate": 0.0001,
        "buffer_size": 10000,
        "gamma": 0.97,
        "exploration_fraction": 0.15,
        "exploration_final_eps": 0.01,
        "learning_starts": 1e4,
        "decay_start_steps": 0,
        "decay_end_steps": 1.5e5
    },
    "VizdoomCorridor-v0": {
        "batch_size": 64,
        "learning_rate": 0.0001,
        "buffer_size": 15000,
        "gamma": 0.957,
        "exploration_fraction": 0.4,
        "exploration_final_eps": 0.001,
        "learning_starts": 4e4,
        "decay_start_steps": 4e4,
        "decay_end_steps": 2.8e5,
    },
    "VizdoomMyWayHome-v0": {
        "batch_size": 64,
        "learning_rate": 0.00001,
        "buffer_size": 10000,
        "gamma": 1,
        "exploration_fraction": 0.1524,
        "exploration_final_eps": 0.1,
        "learning_starts": 100000,
    },
    "VizdoomHealthGathering-v0": {
        "batch_size": 64,
        "learning_rate": 0.00001,
        "buffer_size": 10000,
        "gamma": 1,
        "exploration_fraction": 0.1524,
        "exploration_final_eps": 0.1,
        "learning_starts": 1e4,
    },
    "VizdoomPredictPosition-v0": {
        "batch_size": 64,
        "learning_rate": 0.00001,
        "buffer_size": 15000,
        "gamma": 0.99,
        "exploration_fraction": 0.4,
        "exploration_final_eps": 0.001,
        "learning_starts": 4e4,
        "decay_start_steps": 4e4,
        "decay_end_steps": 2e5,
    },
    "VizdoomTakeCover-v0": {
        "batch_size": 64,
        "learning_rate": 0.001,
        "buffer_size": 15000,
        "gamma": 0.99,
        "exploration_fraction": 0.4,
        "exploration_final_eps": 0.001,
        "learning_starts": 4e4,
        "decay_start_steps": 4e4,
        "decay_end_steps": 2e5,
    }
}

PPO_PARAMS = {
    "VizdoomDefendCenter-v0": {
        "n_steps": 2048,
        "batch_size": 64,
        "learning_rate": 0.0001,
        "gamma": 0.92,
        "gae_lambda": 0.95,
    },
    "VizdoomDefendLine-v0": {
        "n_steps": 2048,
        "batch_size": 64,
        "learning_rate": 0.0001,
        "gamma": 0.94,
        "gae_lambda": 0.93,
    },
    "VizdoomCorridor-v0": {
        "n_steps": 2048,
        "batch_size": 64,
        "learning_rate": 0.0001, # 0.00001
        "gamma": 0.9635,
        "gae_lambda": 0.879,
    },
    "VizdoomMyWayHome-v0": {
        "n_steps": 2048,
        "batch_size": 64,
        "learning_rate": 0.00001,
        "gamma": 0.9345,
        "gae_lambda": 0.8147,
    },
    "VizdoomHealthGathering-v0": {
        "n_steps": 2048,
        "batch_size": 64,
        "learning_rate": 0.00001,
        "gamma": 0.9893,
        "gae_lambda": 0.8687,
    },
    "VizdoomPredictPosition-v0": {
        "n_steps": 2048,
        "batch_size": 64,
        "learning_rate": 0.00001,
        "gamma": 0.94,
        "gae_lambda": 0.93,
    },
    "VizdoomTakeCover-v0": {
        "n_steps": 2048,
        "batch_size": 64,
        "learning_rate": 0.0001,
        "gamma": 0.94,
        "gae_lambda": 0.93,
    }
}
